server:
  port: 3090
spring:
  application:
    name: Yan-music
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.61
    port: 6379
    password: admin123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java # 设置重启的目录
      exclude: WEB-INF/** # classpath目录下的WEB-INF文件内容修改不重启

mybatis-plus:
  type-aliases-package: com.createryan.yanmusic.entity # 别名扫描包

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR # 关闭CONDITIONS EVALUATION REPORT自动配置内容向控制台的输出